name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./      # The folder (relative to the repository root) to publish.
          token: ${{ secrets.GITHUB_TOKEN }}
